### ISSUE TITLE
Observers can use projectiles

### ISSUE THREAD

**Issue by ghost** [dentmaged/Cardinal-Plus#7]

**Comment by dentmaged** [comment]
Please may you be more specific? Like can they shoot a bow? or a snowball?

**Comment by ghost** [comment]
Yes, ender pearls and ender eyes too

**Comment by ryanw-ny** [comment]
@dentmaged @MysticxPvP @TiTo-418 Can you guys at least have the decency to post these issues on the CardinalPGM bug tracker too? Even though this is a hard coded fork its pretty rude to not disclose these issues to the original author. If there is a issue with the original version of the software you guys are building off of, the folks at CardinalPGM need and deserve to know about it. Thanks.
